[package]
name = "rsymtab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["rsymtab_macros"]

[dependencies]
rsymtab_macros = { path = "rsymtab_macros", version = "0.1.0" }
